server:
  port: 8080
  #port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hospital?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    view:
      prefix:  /WEB/views/
      suffix:  .jsp
  servlet:
     multipart:
          #设置单个文件上传大小
     max-file-size: 10MB
          #设置总上传的数据大小
     max-request-size: 50MB

#serverTimezone=UTC
#配置mybatis的信息
#spring集成Mybatis环境
# pojo别名扫描包
#加载Mybatis映射文件
mybatis:
  type-aliases-package: com.chinasoft.hospital_manager.domain
  mapper-locations: classpath:mapper/admin/login/*.xml,mapper/admin/employee/*.xml,mapper/admin/work/*.xml,mapper/admin/patient/*.xml,mapper/admin/doctor/doctorsForPatient/*.xml,
                     mapper/admin/admin/adminForMyself/AdminsForMyselfMapper.xml,mapper/admin/doctor/doctorsForWork/DoctorsForWorkMapper.xml,
                     mapper/admin/doctor/doctorsForMyself/*.xml,mapper/admin/product/*.xml,mapper/admin/pay/*.xml,
                     mapper/admin/examineAndVerify/ExamineAndVerifyMapper.xml




devtools:
  restart:
    # 开启 devtools 热部署功能，支持对项目中的 Java 类的热部署
    enabled: true
    # 设置热部署监控的重启的目录
    additional-paths: src/main/java
    #classpath目录下的WEB-INF文件夹内容修改不重启，但会刷新页面重新加载页面
    exclude: WEB-INF/**
